Exercise

Enhance the Employee Listing Program shown in class today to initialize a table from reading a csv file. Then allow a user to
- add a new employee
- delete an employee
- update an employee information
- list all employees
- give 2% raise or $2,000 whichever is greater to all employees
- dump the table content into a csv file before exiting the program

<b>Make sure your inital data consists minimum of 10 employees.</b>

Challenge 1:
- allow a user to specify a criteria for listing employees such as 
    - employees with x salary or more
    - employees started after x year
    - certain employee

Challenge 2: 
- create a department table and incorporate it into your program

In [3]:
# importing the sqlite module 
import sqlite3

from employee import Employee

In [4]:
dbconn = sqlite3.connect(':memory:')

db = dbconn.cursor()

db.execute("""CREATE TABLE Employees (
            first_name TEXT,
            last_name TEXT,
            salary REAL
            )""")

#commits your transactions into the DATABASE
dbconn.commit()

In [5]:
import csv
allemployees = []
with open("employee.csv") as data_file :
                for line in data_file :
                    allemployees.append(line)

In [14]:


def commandmenu():
    print("""
    commands:
    
    add = add a new employee
    del = delete an employee
    update = update an employee information
    list = list all employees
    raise = give 2% raise or $2,000 whichever is greater to all employees""")
    
commandmenu()
    

    
while True:
    command = input("Command: ")
    command = command.lower()
    if command == 'exit':
        break
    
    if command == "add" :
        name = input("first name")
        last = input("last name")
        salary = int(input("salary"))
        newemployee = []
        newemployee.append(name)
        newemployee.append(last)
        newemployee.append(salary)
        for employee in allemployees :    
            db.execute("INSERT INTO Employees VALUES (?, ?, ?)", (name, last, salary))
            dbconn.commit()
        db.execute(f"SELECT * FROM employees WHERE first_name = '{name}'")
        allemployees.append(db.fetchone())
        
        with open("employee.csv") as data_file :
            csv_data = csv.reader(data_file)

            out_csv_file = open("employee-copy.csv", "w")    
            csv_out = csv.writer(out_csv_file)
            csv_out.writerow(newemployee)
    
            for row in csv_data :
                csv_out.writerow(row)
    
            out_csv_file.close()
    
    elif command == "list" :
        index = 1
        for employee in allemployees:
            print(f"{index}.{employee}")
            index +=1
    elif command == "del" :
        choice = int(input("Number: "))
        if choice < 1 or choice > len(allemployees) :
            print("Invalid movie number.\n")
        else :
            allemployees.pop(choice -1)
    elif command == 'update':
        name = input("first name: ")
        what = input("what do you want to change?(first_name, last_name or salary)")
        to = input("to what?")
        db.execute(f"UPDATE Employees SET {what} = '{to}' WHERE first_name = '{name}'")
        db.fetchall()
        dbconn.commit()
        
    elif command == 'raise':
        db.execute("SELECT salary FROM Employees")
        db.fetchall()
        for employee in allemployees:
            if (db.fetchone()[0])*0.02 > 2000:
                salary = db.fetchone()[0] + 0.02*salary
            else:
                salary = db.fetchone()[0] + 2000
            db.execute("UPDATE Employees SET salary = ?", (salary,))
            
        dbconn.commit()

    else :
        print("Invalid command. Please try again.\n")
        commandmenu()

# save data before exiting



dbconn.commit()
print("Bye")

    commands:

    add = add a new employee
    del = delete an employee
    update = update an employee information
    list = list all employees
    raise = give 2% raise or $2,000 whichever is greater to all employees
Command: list
1.Elmo,Paul,50000

2.Smith,Jems,60000

3.John,Mark,70000

4.Alex,Joseph,80000

5.Lili,Jacob,90000

6.Ruth,Peter,100000

7.George,David,110000

8.Meti,Adam,120000

9.Zinu,Tesfa,130000

10.Baba,Gashe,140000

11.('abebe', 'kebede', 25000.0)
12.('Jambo', 'jote', 40000.0)
13.('X', 'Y', 50000.0)
14.('Betty', 'JEM', 60000.0)
15.('FOO', 'JAMI', 30000.0)
16.('JERY', 'CALID', 36000.0)
17.('JERY', 'CALID', 36000.0)
18.('ABE', 'KEBE', 60000.0)
Command: exit
Bye